### ISSUE TITLE
Installation documentation

### ISSUE THREAD

**Issue by ognjen011** [Showmax/arista-eos-exporter#1]
Do you perhaps have an example of what the prometheus.yaml target needs to look like for this exporter? It is working using curl as described in the docs but how do i  configure  target correctly  for it in prometheus. Something like below i keep getting 404's?

- job_name: arista_exporter
    params:
       url: ['http://10.0.0.1:9200/arista?target=192.168.0.2&modules=tcam,sfp,bgp']
       url: ['http://10.0.0.1:9200/arista?target=192.168.0.1&modules=tcam,sfp,bgp']
    metrics_path: /metrics
    static_configs:
    - targets: ['10.0.0.1:9200']

**Comment by zloo** [comment]
Hi @ognjen011 - can you check whether the example and wording in https://github.com/Showmax/arista-eos-exporter/pull/2/files helps you to set it up?

**Comment by zloo** [comment]
I believe your configuration should look like this:
```yaml
- job_name: 'arista_exporter'
  static_configs:
    - targets:
      - 192.168.0.1
      - 192.168.0.2
  metrics_path: /arista
  params:
    modules: [tcam,sfp,bgp]
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: 10.0.0.1:9200
```
